version: '3'

services:
  subconverter:
    image: tindy2013/subconverter:latest
    container_name: subconverterapi
    restart: always
    ports:
      - 25500:25500

  subconverterweb:
    ## subweb-local:latest是在本地编译的Image，编译仓库为https://github.com/CareyWang/sub-web，
    ## 主要修改了该项目的./src/views/Subconverter.vue文件
    ## 编译命令：docker build -t subweb-local:latest .
    image: subweb-local:latest
    container_name: subweb
    restart: always
    ports:
      - 58080:80
